---
abstract: 'Authorize.Net Customer Information Manager (CIM) Web Services API'
author:
  - 'Fayland Lam <fayland@gmail.com>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.31
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200004, CPAN::Meta::Converter version 2.102400'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Business-AuthorizeNet-CIM
requires:
  LWP::UserAgent: 0
  XML::Simple: 0
  XML::Writer: 0
resources:
  repository: git://github.com/fayland/perl-Business-AuthorizeNet-CIM.git
version: 0.04
